name: AndroidCore

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: Install NDK
      run: $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;25.2.9519653"
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android.zip;
        unzip swift-android.zip;
        swift-android/bin/swift-android tools --update
    - name: Download Android Emulator
      run: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-29;google_apis;x86_64"
    - name: Create Android Emulator
      run: $ANDROID_HOME/tools/bin/avdmanager create avd -n ci-test -k "system-images;android-29;google_apis;x86_64" -d "pixel"
    - name: Start Android Emulator
      run: $ANDROID_HOME/emulator/emulator -no-window -avd ci-test -noaudio > /dev/null &
    - name: Run connected android tests
      run: export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653;
        export SWIFT_ANDROID_ARCH=x86_64;
        export SWIFT_ANDROID_API_LEVEL=24;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        adb wait-for-device;
        cd core;
        swift-test
