name: AndroidApp

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: Install NDK
      run: $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;25.2.9519653"
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android.zip;
        unzip swift-android.zip;
        swift-android/bin/swift-android tools --update
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build all variants
      run: export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653;
        export SWIFT_ANDROID_ARCH=x86_64;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        cd android;
        echo "API_KEY=XXXYYYZZZ" >> local.properties;
        ./gradlew app:buildRelease
