name: AndroidApp

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: Install Swift toolchain 5.4.2
      run: wget https://swift.org/builds/swift-5.4.2-release/xcode/swift-5.4.2-RELEASE/swift-5.4.2-RELEASE-osx.pkg;
        sudo installer -pkg swift-5.4.2-RELEASE-osx.pkg -target /
    - name: Install NDK
      run: wget https://dl.google.com/android/repository/android-ndk-r21e-darwin-x86_64.zip;
        unzip android-ndk-r21e-darwin-x86_64.zip
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android-5.4-r4.zip;
        unzip swift-android-5.4-r4.zip;
        rm -rf swift-android-5.4-r4.zip;
        swift-android-5.4-r4/bin/swift-android tools --update;
        ln -sfn swift-android-5.4-r4 swift-android-current
    - name: Build all variants
      run: export TOOLCHAINS=org.swift.540202104261a;
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e;
        export SWIFT_ANDROID_ARCH=x86_64;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android-current;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        cd android;
        echo "API_KEY=XXXYYYZZZ" >> local.properties;
        ./gradlew app:build
